import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js';
import {MovementController} from './game/movementController.js';
import {WeaponController,WEAPONS} from './game/weaponSystem.js';
import {damageFalloff,recoilKick} from './game/combatPhysics.js';
const $=id=>document.getElementById(id);let scene,camera,renderer,clock,player,playerBody,movement,weapons;let enemies=[];let running=false,health=100,teamScore=0,enemyScore=0,timeLeft=180,aimKick=0;const keys={};let move={x:0,y:0};
function init3D(){scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);scene.fog=new THREE.Fog(0x071018,22,70);camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);renderer.domElement.style.cssText='position:fixed;inset:0;z-index:0;pointer-events:none';clock=new THREE.Clock();scene.add(new THREE.HemisphereLight(0xb9e9ff,0x172027,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(10,20,8);sun.castShadow=true;scene.add(sun);createArena();createPlayer();for(let i=0;i<5;i++)spawnEnemy(i);renderer.setAnimationLoop(loop)}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.08})}function box(x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.castShadow=true;m.receiveShadow=true;return m}
function createArena(){const floor=box(42,.5,30,0x17252d);floor.position.y=-.25;scene.add(floor);[[0,3,-15,42,6,.6],[0,3,15,42,6,.6],[-21,3,0,.6,6,30],[21,3,0,.6,6,30]].forEach(a=>{const w=box(a[3],a[4],a[5],0x253840);w.position.set(a[0],a[1],a[2]);scene.add(w)});for(let i=0;i<13;i++){const o=box(THREE.MathUtils.randFloat(2,5),THREE.MathUtils.randFloat(1.2,3),THREE.MathUtils.randFloat(1.5,4),0x31464e);o.position.set(THREE.MathUtils.randFloat(-17,17),o.geometry.parameters.height/2,THREE.MathUtils.randFloat(-11,11));scene.add(o)}}
function createPlayer(){player=new THREE.Group();playerBody=box(1,1.8,.75,0x54d9f4);playerBody.position.y=1.15;player.add(playerBody);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,10),mat(0xe7b98b));head.position.y=2.35;player.add(head);scene.add(player);player.position.set(0,0,10);movement=new MovementController();weapons=new WeaponController(WEAPONS.AR01)}
function spawnEnemy(i){const e=new THREE.Group(),body=box(1,1.8,.75,0xe65f6a);body.position.y=1.15;e.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,10),mat(0xdba47c));head.position.y=2.35;e.add(head);e.position.set((i%2?1:-1)*THREE.MathUtils.randFloat(7,16),0,THREE.MathUtils.randFloat(-9,9));e.userData={hp:100,shootAt:0,alive:true,speed:2.4+Math.random()*.8,phase:Math.random()*6,nextDodge:0,dodge:0};scene.add(e);enemies.push(e)}
function startMatch(){if(renderer){renderer.setAnimationLoop(null);renderer.domElement.remove()}scene=null;camera=null;renderer=null;enemies=[];init3D();$('menu').classList.add('hidden');$('loadout').classList.add('hidden');$('result').classList.add('hidden');$('hud').classList.remove('hidden');running=true;health=100;teamScore=enemyScore=0;timeLeft=180;updateHUD()}
function shoot(){if(!running)return;const now=performance.now();if(!weapons.fire(now))return;aimKick=recoilKick(aimKick,weapons.def.recoil,.016);const forward=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion);let best=null,bd=Infinity;for(const e of enemies){if(!e.userData.alive)continue;const d=e.position.distanceTo(player.position);if(d>=bd||d>weapons.def.range)continue;const dir=e.position.clone().add(new THREE.Vector3(0,1.2,0)).sub(player.position).normalize();if(forward.dot(dir)>.48){best=e;bd=d}}if(best){best.userData.hp-=weapons.def.damage*damageFalloff(bd,8,weapons.def.range,.45);if(best.userData.hp<=0){best.userData.alive=false;best.visible=false;teamScore++;addFeed('YOU','ELIMINATED');setTimeout(()=>{if(!best)return;best.position.set(THREE.MathUtils.randFloat(-16,16),0,THREE.MathUtils.randFloat(-10,10));best.userData.hp=100;best.userData.alive=true;best.visible=true},900)}}updateHUD()}
function addFeed(a,b){const d=document.createElement('div');d.textContent=`${a}  ${b}`;$('killfeed').prepend(d);setTimeout(()=>d.remove(),2200)}function reload(){weapons.reload().then(updateHUD)}function damage(){health=Math.max(0,health-8);$('damageFlash').style.opacity=.8;setTimeout(()=>$('damageFlash').style.opacity=0,100);if(health<=0){enemyScore++;addFeed('YOU','DOWN');player.position.set(0,0,10);movement=new MovementController();health=100}updateHUD()}
function updateHUD(){$('healthFill').style.width=health+'%';$('healthText').textContent=Math.round(health);$('ammo').textContent=weapons?.ammo??0;$('weaponName').textContent=weapons?.def.name??'AR-01';$('teamScore').textContent=teamScore;$('enemyScore').textContent=enemyScore}
function loop(){if(!running){renderer.render(scene,camera);return}const dt=Math.min(clock.getDelta(),.05);timeLeft-=dt;if(timeLeft<=0||teamScore>=10||enemyScore>=10){endMatch();return}const x=move.x+(keys.KeyD?1:0)-(keys.KeyA?1:0),z=move.y+(keys.KeyS?1:0)-(keys.KeyW?1:0),mag=Math.min(1,Math.hypot(x,z));const input={x:x/(mag||1),z:z/(mag||1),magnitude:mag,sprint:keys.ShiftLeft||keys.ShiftRight,crouch:keys.KeyC||keys.Control,slide:keys.KeyC||keys.Control,jump:keys.Space};movement.update(input,dt);movement.applyTo(player.position,dt);playerBody.scale.y=movement.state==='SLIDE'?.62:1;const v=movement.velocity;if(mag>.05)player.rotation.y=Math.atan2(v.x,v.z);const now=performance.now();for(const e of enemies){if(!e.userData.alive)continue;const to=player.position.clone().sub(e.position),d=to.length();if(now>e.userData.nextDodge){e.userData.nextDodge=now+500+Math.random()*900;e.userData.dodge=(Math.random()-.5)*1.6}if(d>3){to.y=0;to.normalize();const side=new THREE.Vector3(-to.z,0,to.x).multiplyScalar(e.userData.dodge);e.position.addScaledVector(to.add(side).normalize(),e.userData.speed*dt)}else if(now>e.userData.shootAt){e.userData.shootAt=now+650+Math.random()*550;damage()}e.lookAt(player.position.x,1,e.position.z)}aimKick=Math.max(0,aimKick-dt*2);camera.position.lerp(new THREE.Vector3(player.position.x,7.2,player.position.z+11),.09);camera.lookAt(player.position.x,1.2+aimKick,player.position.z);$('timer').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(Math.floor(timeLeft%60)).padStart(2,'0')}`;updateHUD();renderer.render(scene,camera)}
function endMatch(){running=false;$('hud').classList.add('hidden');$('result').classList.remove('hidden');$('finalTeam').textContent=teamScore;$('finalEnemy').textContent=enemyScore;$('resultTitle').textContent=teamScore>enemyScore?'VICTORY':'DEFEAT'}
function setup(){$('playBtn').onclick=startMatch;$('startLoadout').onclick=startMatch;$('loadoutBtn').onclick=()=>$('loadout').classList.remove('hidden');$('closeLoadout').onclick=()=>$('loadout').classList.add('hidden');$('againBtn').onclick=()=>{$('result').classList.add('hidden');startMatch()};$('menuBtn').onclick=()=>{$('result').classList.add('hidden');$('menu').classList.remove('hidden')};$('shootBtn').onpointerdown=shoot;$('reloadBtn').onclick=reload;$('pauseBtn').onclick=()=>{running=!running;if(running)clock.start()};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload()});addEventListener('keyup',e=>keys[e.code]=false);let joy=$('joystick'),active=false;joy.onpointerdown=e=>{active=true;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(active)joyMove(e)};joy.onpointerup=joy.onpointercancel=()=>{active=false;move.x=move.y=0;joy.querySelector('.stick').style.transform='translate(-50%,-50%)'};function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);move.x=Math.cos(a)*m/42;move.y=Math.sin(a)*m/42;joy.querySelector('.stick').style.transform=`translate(calc(-50% + ${move.x*42}px),calc(-50% + ${move.y*42}px))`}addEventListener('resize',()=>{if(camera){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}})}setup();
