import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js';
import {MovementController} from './game/movementController.js';
import {WeaponController,WEAPONS} from './game/weaponSystem.js';
import {damageFalloff} from './game/combatPhysics.js';
import {MobileCombatController,rayDirection} from './game/mobileCombat.js';
import {createOperator,Operators,setLocomotionPose} from './game/characterRig.js';
import {createWeapon,muzzleFlash} from './game/weaponModel.js';
import {createCombatFx} from './game/fxSystem.js';
import {chooseCombatPosition,clampPosition} from './game/coverNavigation.js';
import {CombatCamera} from './game/cameraCombat.js';
import {WeaponFeedback} from './game/weaponFeedback.js';
import {EquipmentController,EquipmentSlot} from './game/equipmentSystem.js';
import {EquipmentInput} from './game/equipmentInput.js';
import {createMeleeVisual,createGrenadeVisual} from './game/equipmentVisuals.js';
import {MeleeGrenadeCombat} from './game/meleeGrenadeCombat.js';
import {createGrenadeRuntime} from './game/grenadeVisualRuntime.js';
const $=id=>document.getElementById(id);let scene,camera,renderer,clock,player,movement,weapons,mobile,fx,playerWeapon,meleeVisual,grenadeVisual,flash,combatCamera,weaponFeedback,equipment,equipmentInput,equipmentCombat,grenadeRuntime;let enemies=[];let running=false,paused=false,health=100,teamScore=0,enemyScore=0,timeLeft=180;const keys={};let move={x:0,y:0};
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.68,metalness:.12})}function box(x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.castShadow=true;m.receiveShadow=true;return m}
function init3D(){scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);scene.fog=new THREE.Fog(0x071018,24,70);camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);renderer.domElement.style.cssText='position:fixed;inset:0;z-index:0;pointer-events:none';clock=new THREE.Clock();fx=createCombatFx(THREE);scene.add(new THREE.HemisphereLight(0xb9e9ff,0x172027,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(10,20,8);sun.castShadow=true;scene.add(sun);createArena();createPlayer();for(let i=0;i<5;i++)spawnEnemy(i);grenadeRuntime=createGrenadeRuntime(THREE,scene);renderer.setAnimationLoop(loop)}
function createArena(){const floor=box(42,.5,30,0x17252d);floor.position.y=-.25;scene.add(floor);[[0,3,-15,42,6,.6],[0,3,15,42,6,.6],[-21,3,0,.6,6,30],[21,3,0,.6,6,30]].forEach(a=>{const w=box(a[3],a[4],a[5],0x253840);w.position.set(a[0],a[1],a[2]);scene.add(w)});const covers=[[-10,1.2,-5,3,2.4,2],[-3,1.5,4,4,3,2],[6,1.1,-4,2.5,2.2,3],[12,1.8,6,3,3.6,2],[-13,1.3,7,4,2.6,2],[1,1.4,-8,3,2.8,2]];for(const c of covers){const o=box(c[3],c[1]*2,c[5],0x31464e);o.position.set(c[0],c[1],c[2]);scene.add(o)}}
function createPlayer(){player=createOperator(THREE,Operators.REX);scene.add(player);player.position.set(0,0,10);movement=new MovementController();weapons=new WeaponController(WEAPONS.AR01);weaponFeedback=new WeaponFeedback();equipment=new EquipmentController();equipmentCombat=new MeleeGrenadeCombat();playerWeapon=createWeapon(THREE,'AR01');meleeVisual=createMeleeVisual(THREE);grenadeVisual=createGrenadeVisual(THREE);playerWeapon.position.set(.48,1.25,.25);playerWeapon.rotation.y=Math.PI;meleeVisual.position.set(.48,1.22,.32);grenadeVisual.position.set(.5,1.3,.28);player.add(playerWeapon,meleeVisual,grenadeVisual);flash=muzzleFlash(THREE);flash.position.set(.48,1.3,.98);player.add(flash);setEquipmentVisual(EquipmentSlot.WEAPON);combatCamera=new CombatCamera(camera)}
function setEquipmentVisual(slot){playerWeapon.visible=slot===EquipmentSlot.WEAPON;meleeVisual.visible=slot===EquipmentSlot.MELEE;grenadeVisual.visible=slot===EquipmentSlot.GRENADE;flash.visible=false;player.userData.activeEquipment=slot;equipmentInput?.setActive(slot);updateHUD()}
function selectEquipment(slot){if(!running||!equipment)return;if(equipment.switchTo(slot)){setEquipmentVisual(slot)}}
function action(){if(!running||paused||equipment.switching)return;const slot=equipment.activeSlot;const look=mobile?.getLook()||{yaw:player.rotation.y,pitch:0};const dir=rayDirection(look.yaw,look.pitch);if(slot===EquipmentSlot.WEAPON){shoot();return}if(slot===EquipmentSlot.MELEE){const hit=equipmentCombat.melee(.05,player,enemies);if(hit){fx.burst(hit.position.clone().add(new THREE.Vector3(0,1.2,0)));if(hit.userData.hp<=0)eliminateEnemy(hit)}return}const p=equipmentCombat.throwGrenade(player,dir);if(p){grenadeRuntime.spawn(p,grenadeVisual)}}
function eliminateEnemy(e){if(!e.userData.alive)return;e.userData.alive=false;e.visible=false;teamScore++;addFeed('YOU','ELIMINATED');setTimeout(()=>{e.position.set(THREE.MathUtils.randFloat(-16,16),0,THREE.MathUtils.randFloat(-10,10));e.userData.hp=100;e.userData.alive=true;e.visible=true},900)}
function spawnEnemy(i){const choices=[Operators.NYX,Operators.TITAN,Operators.VEX];const e=createOperator(THREE,choices[i%choices.length]);e.position.set((i%2?1:-1)*THREE.MathUtils.randFloat(7,16),0,THREE.MathUtils.randFloat(-9,9));e.userData={hp:100,shootAt:0,alive:true,speed:2.3+Math.random()*1.1,nextDodge:0,dodge:0};scene.add(e);enemies.push(e)}
function startMatch(){if(renderer){renderer.setAnimationLoop(null);renderer.domElement.remove();renderer.dispose()}document.getElementById('lookZone')?.remove();['equipWeapon','equipMelee','equipGrenade','equipmentBar'].forEach(id=>document.getElementById(id)?.remove());scene=null;camera=null;renderer=null;enemies=[];paused=false;init3D();mobile=new MobileCombatController(document);equipmentInput=new EquipmentInput(selectEquipment,action);$('menu').classList.add('hidden');$('loadout').classList.add('hidden');$('result').classList.add('hidden');$('hud').classList.remove('hidden');running=true;health=100;teamScore=enemyScore=0;timeLeft=180;selectEquipment(EquipmentSlot.WEAPON);updateHUD()}
function shoot(){if(!running||paused||equipment?.activeSlot!==EquipmentSlot.WEAPON)return;const now=performance.now();if(!weapons.fire(now))return;weaponFeedback.fire(now,weapons.def.recoil);combatCamera?.kick(weapons.def.recoil);flash.visible=true;setTimeout(()=>{if(flash)flash.visible=false},55);const l=mobile?.getLook()||{yaw:player.rotation.y,pitch:0};const d0=rayDirection(l.yaw,l.pitch);const forward=new THREE.Vector3(d0.x,d0.y,d0.z);let best=null,bd=Infinity;for(const e of enemies){if(!e.userData.alive)continue;const d=e.position.distanceTo(player.position);if(d>=bd||d>weapons.def.range)continue;const dir=e.position.clone().add(new THREE.Vector3(0,1.2,0)).sub(player.position).normalize();if(forward.dot(dir)>.72){best=e;bd=d}}if(best){best.userData.hp-=weapons.def.damage*damageFalloff(bd,8,weapons.def.range,.45);fx.burst(best.position.clone().add(new THREE.Vector3(0,1.2,0)));if(best.userData.hp<=0)eliminateEnemy(best)}updateHUD()}
function addFeed(a,b){const d=document.createElement('div');d.textContent=`${a}  ${b}`;$('killfeed').prepend(d);setTimeout(()=>d.remove(),2200)}function reload(){if(running&&!paused&&equipment?.activeSlot===EquipmentSlot.WEAPON)weapons.reload().then(updateHUD)}function damage(){health=Math.max(0,health-8);const f=$('damageFlash');if(f){f.style.opacity=.8;setTimeout(()=>f.style.opacity=0,100)}if(health<=0){enemyScore++;addFeed('YOU','DOWN');player.position.set(0,0,10);movement=new MovementController();health=100}updateHUD()}
function updateHUD(){$('healthFill').style.width=health+'%';$('healthText').textContent=Math.round(health);$('ammo').textContent=equipment?.activeSlot===EquipmentSlot.WEAPON?(weapons?.ammo??0):'';$('weaponName').textContent=equipment?.activeSlot===EquipmentSlot.MELEE?'KINETIC BLADE':equipment?.activeSlot===EquipmentSlot.GRENADE?`FRAG GRENADE (${equipmentCombat?.grenades??0})`:weapons?.def.name??'AR-01';$('teamScore').textContent=teamScore;$('enemyScore').textContent=enemyScore}
function loop(){if(!running){renderer.render(scene,camera);return}if(paused){renderer.render(scene,camera);return}const dt=Math.min(clock.getDelta(),.05);timeLeft-=dt;if(timeLeft<=0||teamScore>=10||enemyScore>=10){endMatch();return}const look=mobile?.getLook()||{yaw:player.rotation.y,pitch:0};const x=move.x+(keys.KeyD?1:0)-(keys.KeyA?1:0),z=move.y+(keys.KeyS?1:0)-(keys.KeyW?1:0),mag=Math.min(1,Math.hypot(x,z));const input={x:x/(mag||1),z:z/(mag||1),magnitude:mag,sprint:keys.ShiftLeft||keys.ShiftRight,crouch:keys.KeyC||keys.Control,slide:keys.KeyC||keys.Control,jump:keys.Space};movement.update(input,dt);movement.applyTo(player.position,dt);const bounded=clampPosition(player.position);player.position.x=bounded.x;player.position.z=bounded.z;setLocomotionPose(player,movement.state,dt);player.rotation.y=look.yaw;const now=performance.now();for(const e of enemies){if(!e.userData.alive)continue;const target={x:player.position.x,z:player.position.z};const ep={x:e.position.x,z:e.position.z};const desired=chooseCombatPosition({position:ep},target);const dx=desired.x-e.position.x,dz=desired.z-e.position.z;const dl=Math.hypot(dx,dz)||1;e.position.x+=dx/dl*e.userData.speed*dt;e.position.z+=dz/dl*e.userData.speed*dt;const eb=clampPosition(e.position);e.position.x=eb.x;e.position.z=eb.z;if(now>e.userData.nextDodge){e.userData.nextDodge=now+350+Math.random()*900;e.userData.dodge=(Math.random()-.5)*2.2}if(Math.hypot(player.position.x-e.position.x,player.position.z-e.position.z)<4){e.position.x+=e.userData.dodge*dt;e.position.z-=e.userData.dodge*dt}if(now>e.userData.shootAt&&Math.hypot(player.position.x-e.position.x,player.position.z-e.position.z)<24){e.userData.shootAt=now+650+Math.random()*550;damage()}e.lookAt(player.position.x,1.2,player.position.z);setLocomotionPose(e,Math.hypot(dx,dz)>.15?'walk':'idle',dt)}equipmentCombat.updateGrenades(dt,enemies);grenadeRuntime.update(equipmentCombat.projectiles,fx);combatCamera.yaw=look.yaw;combatCamera.pitch=look.pitch;combatCamera.update(player.position,dt);const feedback=weaponFeedback.update(dt);if(feedback.flash<=0)flash.visible=false;$('timer').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(Math.floor(timeLeft%60)).padStart(2,'0')}`;fx.update(dt,scene);updateHUD();renderer.render(scene,camera)}
function endMatch(){running=false;$('hud').classList.add('hidden');$('result').classList.remove('hidden');$('finalTeam').textContent=teamScore;$('finalEnemy').textContent=enemyScore;$('resultTitle').textContent=teamScore>enemyScore?'VICTORY':'DEFEAT'}
function setup(){$('playBtn').onclick=startMatch;$('startLoadout').onclick=startMatch;$('loadoutBtn').onclick=()=>$('loadout').classList.remove('hidden');$('closeLoadout').onclick=()=>$('loadout').classList.add('hidden');$('againBtn').onclick=()=>{$('result').classList.add('hidden');startMatch()};$('menuBtn').onclick=()=>{$('result').classList.add('hidden');$('menu').classList.remove('hidden')};$('shootBtn').onpointerdown=action;$('reloadBtn').onclick=reload;$('pauseBtn').onclick=()=>{paused=!paused;if(!paused)clock.start()};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload();if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false);let joy=$('joystick'),active=false;joy.onpointerdown=e=>{active=true;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(active)joyMove(e)};joy.onpointerup=joy.onpointercancel=()=>{active=false;move.x=move.y=0;joy.querySelector('.stick').style.transform='translate(-50%,-50%)'};function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);move.x=Math.cos(a)*m/42;move.y=Math.sin(a)*m/42;joy.querySelector('.stick').style.transform=`translate(calc(-50% + ${move.x*42}px),calc(-50% + ${move.y*42}px))`}addEventListener('resize',()=>{if(camera){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}})}setup();