import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js';

const $=id=>document.getElementById(id);let scene,camera,renderer,clock,player,playerBody;let enemies=[];let running=false,health=100,ammo=30,teamScore=0,enemyScore=0,timeLeft=180,lastShot=0;const keys={};let move={x:0,y:0};

function init3D(){scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);scene.fog=new THREE.Fog(0x071018,22,70);camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,100);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);renderer.domElement.style.cssText='position:fixed;inset:0;z-index:0;pointer-events:none';clock=new THREE.Clock();
const hemi=new THREE.HemisphereLight(0xb9e9ff,0x172027,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(10,20,8);sun.castShadow=true;scene.add(sun);createArena();createPlayer();for(let i=0;i<5;i++)spawnEnemy(i);renderer.setAnimationLoop(loop)}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.08})}
function box(x,y,z,c){const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.castShadow=true;m.receiveShadow=true;return m}
function createArena(){const floor=box(42,.5,30,0x17252d);floor.position.y=-.25;scene.add(floor);const wallMat=0x253840;[[0,3,-15,42,6,.6],[0,3,15,42,6,.6],[-21,3,0,.6,6,30],[21,3,0,.6,6,30]].forEach(a=>{const w=box(a[3],a[4],a[5],wallMat);w.position.set(a[0],a[1],a[2]);scene.add(w)});for(let i=0;i<13;i++){const o=box(THREE.MathUtils.randFloat(2,5),THREE.MathUtils.randFloat(1.2,3),THREE.MathUtils.randFloat(1.5,4),0x31464e);o.position.set(THREE.MathUtils.randFloat(-17,17),o.geometry.parameters.height/2-.0,THREE.MathUtils.randFloat(-11,11));scene.add(o)} }
function createPlayer(){player=new THREE.Group();playerBody=box(1,1.8,.75,0x54d9f4);playerBody.position.y=1.15;player.add(playerBody);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,10),mat(0xe7b98b));head.position.y=2.35;player.add(head);scene.add(player);player.position.set(0,0,10)}
function spawnEnemy(i){const e=new THREE.Group();const body=box(1,1.8,.75,0xe65f6a);body.position.y=1.15;e.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,10),mat(0xdba47c));head.position.y=2.35;e.add(head);e.position.set((i%2?1:-1)*THREE.MathUtils.randFloat(7,16),0,THREE.MathUtils.randFloat(-9,9));e.userData={hp:100,shootAt:0,alive:true};scene.add(e);enemies.push(e)}
function startMatch(){init3D();$('menu').classList.add('hidden');$('loadout').classList.add('hidden');$('hud').classList.remove('hidden');running=true;health=100;ammo=30;teamScore=enemyScore=0;timeLeft=180;updateHUD()}
function shoot(){if(!running||ammo<=0)return;const now=performance.now();if(now-lastShot<120)return;lastShot=now;ammo--;let best=null,bd=999;enemies.forEach(e=>{if(!e.userData.alive)return;const d=e.position.distanceTo(player.position);if(d<bd&&d<18){const dir=e.position.clone().sub(player.position).normalize();const f=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion);if(f.dot(dir)>.45){best=e;bd=d}}});if(best){best.userData.hp-=34;if(best.userData.hp<=0){best.userData.alive=false;best.visible=false;teamScore++;addFeed('YOU','ELIMINATED');setTimeout(()=>{best.position.set(THREE.MathUtils.randFloat(-16,16),0,THREE.MathUtils.randFloat(-10,10));best.userData.hp=100;best.userData.alive=true;best.visible=true},1200)}}updateHUD()}
function addFeed(a,b){const d=document.createElement('div');d.textContent=`${a}  ${b}`;$('killfeed').prepend(d);setTimeout(()=>d.remove(),2200)}
function reload(){ammo=30;updateHUD()}
function damage(){health=Math.max(0,health-8);$('damageFlash').style.opacity=.8;setTimeout(()=>$('damageFlash').style.opacity=0,100);if(health<=0){enemyScore++;addFeed('YOU','DOWN');player.position.set(0,0,10);health=100}updateHUD()}
function updateHUD(){$('healthFill').style.width=health+'%';$('healthText').textContent=health;$('ammo').textContent=ammo;$('teamScore').textContent=teamScore;$('enemyScore').textContent=enemyScore}
function loop(){if(!running){renderer.render(scene,camera);return}const dt=Math.min(clock.getDelta(),.05);timeLeft-=dt;if(timeLeft<=0||teamScore>=10||enemyScore>=10){endMatch();return}const speed=7;let x=move.x+(keys.KeyD?1:0)-(keys.KeyA?1:0),z=move.y+(keys.KeyS?1:0)-(keys.KeyW?1:0);const v=new THREE.Vector3(x,0,z);if(v.lengthSq()>0){v.normalize();player.position.addScaledVector(v,speed*dt);player.rotation.y=Math.atan2(v.x,v.z)}player.position.x=THREE.MathUtils.clamp(player.position.x,-19.5,19.5);player.position.z=THREE.MathUtils.clamp(player.position.z,-13.5,13.5);enemies.forEach(e=>{if(!e.userData.alive)return;const d=e.position.distanceTo(player.position);if(d>3){e.position.lerp(player.position,dt*.28);e.lookAt(player.position.x,1,e.position.z)}else if(performance.now()>e.userData.shootAt){e.userData.shootAt=performance.now()+900;damage()}});camera.position.lerp(new THREE.Vector3(player.position.x,7.5,player.position.z+11),.09);camera.lookAt(player.position.x,1.2,player.position.z);$('timer').textContent=`${String(Math.floor(timeLeft/60)).padStart(2,'0')}:${String(Math.floor(timeLeft%60)).padStart(2,'0')}`;updateHUD();renderer.render(scene,camera)}
function endMatch(){running=false;$('hud').classList.add('hidden');$('result').classList.remove('hidden');$('finalTeam').textContent=teamScore;$('finalEnemy').textContent=enemyScore;$('resultTitle').textContent=teamScore>enemyScore?'VICTORY':'DEFEAT'}
function setup(){ $('playBtn').onclick=startMatch;$('startLoadout').onclick=startMatch;$('loadoutBtn').onclick=()=>$('loadout').classList.remove('hidden');$('closeLoadout').onclick=()=>$('loadout').classList.add('hidden');$('againBtn').onclick=()=>{$('result').classList.add('hidden');startMatch()};$('menuBtn').onclick=()=>{$('result').classList.add('hidden');$('menu').classList.remove('hidden')};$('shootBtn').onpointerdown=shoot;$('reloadBtn').onclick=reload;$('pauseBtn').onclick=()=>running=!running;addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space')shoot();if(e.code==='KeyR')reload()});addEventListener('keyup',e=>keys[e.code]=false);let joy=$('joystick'),active=false;joy.onpointerdown=e=>{active=true;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(active)joyMove(e)};joy.onpointerup=joy.onpointercancel=()=>{active=false;move.x=move.y=0;joy.querySelector('.stick').style.transform='translate(-50%,-50%)'};function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);move.x=Math.cos(a)*m/42;move.y=Math.sin(a)*m/42;joy.querySelector('.stick').style.transform=`translate(calc(-50% + ${move.x*42}px),calc(-50% + ${move.y*42}px))`}addEventListener('resize',()=>{if(camera){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}})}setup();
